### ISSUE TITLE
Support for Java 17

### ISSUE THREAD

**Issue by jokraehe** [MutabilityDetector/MutabilityDetector#185]
Hi @Grundlefleck,

any chances you want to merge #182? We want to upgrade to Java 17 and MutabilityDetector ist not working for us anymore.

```
Class being analysed: java.lang.ref.SoftReference
Checker that failed: CanSubclassChecker
Classes analysed so far:

An unhandled error occurred while analysing the class 'java.lang.ref.SoftReference'.

This is probably my fault, not yours, and I am sorry.
I'd love to get an opportunity to fix this, please report as an issue at:
 https://github.com/MutabilityDetector/MutabilityDetector/issues/ 
Pasting in this error message and stack trace, and if possible, 
information about the code causing the error. 
For example, one of: 
    .class files (preferably with source);
    compilable .java files; 
    a jar (again preferably with source);
    or, if your project is open source, information on where I can get the code from
        (I'm happy to checkout and build your project in order to investigate the error).

Apologies, and thank you for using Mutability Detector.


	at org.mutabilitydetector.checkers.UnhandledExceptionBuilder.unhandledException(UnhandledExceptionBuilder.java:62)
	at org.mutabilitydetector.checkers.CheckerRunner.attemptRecovery(CheckerRunner.java:121)
	at org.mutabilitydetector.checkers.CheckerRunner.runVisitor(CheckerRunner.java:89)
	at org.mutabilitydetector.checkers.CheckerRunner.run(CheckerRunner.java:69)
	at org.mutabilitydetector.checkers.AllChecksRunner.runCheckers(AllChecksRunner.java:75)
	at org.mutabilitydetector.DefaultCachingAnalysisSession.requestAnalysis(DefaultCachingAnalysisSession.java:141)
	at org.mutabilitydetector.DefaultCachingAnalysisSession.processTransitiveAnalysis(DefaultCachingAnalysisSession.java:125)
	at org.mutabilitydetector.checkers.info.MutableTypeInformation.requestAnalysisIfNoCyclicReferenceDetected(MutableTypeInformation.java:67)
	at org.mutabilitydetector.checkers.info.MutableTypeInformation.resultOf(MutableTypeInformation.java:59)
	at org.mutabilitydetector.checkers.MutableTypeToFieldChecker$AssignMutableTypeToFieldChecker.checkIfClassIsMutable(MutableTypeToFieldChecker.java:174)
	at org.mutabilitydetector.checkers.MutableTypeToFieldChecker$AssignMutableTypeToFieldChecker.visitFieldAssignmentFrame(MutableTypeToFieldChecker.java:156)
	at org.mutabilitydetector.checkers.FieldAssignmentVisitor.visitEnd(FieldAssignmentVisitor.java:92)
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1492)
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:718)
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.accept(ClassReader.java:401)
	at org.mutabilitydetector.checkers.CheckerRunner.analyse(CheckerRunner.java:112)
	at org.mutabilitydetector.checkers.CheckerRunner.analyseFromClassLoader(CheckerRunner.java:107)
	at org.mutabilitydetector.checkers.CheckerRunner.runVisitor(CheckerRunner.java:86)
	... 50 more
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.mutabilitydetector.internal.org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at org.mutabilitydetector.checkers.CheckerRunner.analyse(CheckerRunner.java:111)
	at org.mutabilitydetector.checkers.CheckerRunner.analyseFromClassLoader(CheckerRunner.java:107)
	at org.mutabilitydetector.checkers.CheckerRunner.runVisitor(CheckerRunner.java:86)
	... 65 more
```

**Comment by jokraehe** [comment]
This seems to be the same issue as described in #181

**Comment by Grundlefleck** [comment]
I've merged #181 which should add support. I've run out of time this evening to cut the release, but progress is being made.

**Comment by Grundlefleck** [comment]
@jokraehe  0.10.6 has just landed in Maven Central. Please try it out and let me know if it fixes the issue.

**Comment by jokraehe** [comment]
Version 0.10.6 works fine with Java 17. Thank you very much!

**Comment by meowpunch** [comment]
Did it really work with `record class` as well? Even though using with 0.10.6, I got same error message.
