### ISSUE TITLE
ClassNotFoundException when Guava is not on the classpath

### ISSUE THREAD

**Issue by danielFesenmeyerAtBosch** [MutabilityDetector/MutabilityDetector#59]
With the currently released version (0.9.3) I get the following exception:

```
java.lang.ExceptionInInitializerError
	at org.mutabilitydetector.unittesting.MutabilityAssert.<clinit>(MutabilityAssert.java:658)
	...
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: org.mutabilitydetector.checkers.MutabilityAnalysisException: Error in configuration: Class not  found: com.google.common.collect.Lists
	at org.mutabilitydetector.ConfigurationBuilder.rethrow(ConfigurationBuilder.java:447)
	at org.mutabilitydetector.ConfigurationBuilder.hardcodeValidCopyMethod(ConfigurationBuilder.java:432)
	at org.mutabilitydetector.config.GuavaConfiguration.configure(GuavaConfiguration.java:37)
	at org.mutabilitydetector.ConfigurationBuilder.build(ConfigurationBuilder.java:148)
	at org.mutabilitydetector.Configurations.<clinit>(Configurations.java:39)
	... 25 more
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.Lists
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:260)
	at org.mutabilitydetector.ConfigurationBuilder.hardcodeValidCopyMethod(ConfigurationBuilder.java:424)
	... 28 more

```

With version 0.9.2 the exception does **not** occur.

**Comment by Grundlefleck** [comment]
Thanks for reporting, and apologies. Will get a fix pushed out in the next few days.

**Comment by danielFesenmeyerAtBosch** [comment]
Thanks, no problem.

**Comment by Grundlefleck** [comment]
Hi @danielFesenmeyerAtBosch, just released 0.9.4 to Maven Central, which should fix this issue.

**Comment by Grundlefleck** [comment]
Bah, made a dumb mistake when releasing. 0.9.4 doesn't fix. Will fix properly soon.

**Comment by Grundlefleck** [comment]
0.9.5 is on it's way to Maven Central, it should contain the actual fix.

**Comment by danielFesenmeyerAtBosch** [comment]
Thanks, @Grundlefleck. I've just tested it. Works fine now.
