### ISSUE TITLE
Problems cloning class generated by wsimport

### ISSUE THREAD

**Issue by more10** [MutabilityDetector/MutabilityDetector#82]
Code:
`<dependency org="org.jadira.cloning" name="cloning" rev="3.1.0.CR10"/>
`

`private static BasicCloner cloner = new BasicCloner();
`
   ```

  Adresspost laggTill1 = skapaAdressPostAllaFalt(e, "allén", null, null);
  Adresspost uppdatera = cloner.clone(laggTill1);

```

[Adresspost.zip](https://github.com/MutabilityDetector/MutabilityDetector/files/212870/Adresspost.zip)

Exception:

```

org.mutabilitydetector.checkers.MutabilityAnalysisException: 
An unhandled error occurred. Please read message at end of this output.

Class being analysed: se.xxxxx.schema.integration.isperson.personinformation._2.Adresspost
Checker that failed: CanSubclassChecker
Classes analysed so far:

An unhandled error occurred. This is probably my fault, not yours, and I am sorry.
I'd love to get an opportunity to fix this, please report as an issue at:
 https://github.com/MutabilityDetector/MutabilityDetector/issues/ 
Pasting in this error message and stack trace, and if possible, 
information about the code causing the error. 
For example, one of: 
    .class files (preferably with source);
    compilable .java files; 
    a jar (again preferably with source);
    or, if your project is open source, information on where I can get the code from
        (I'm happy to checkout and build your project in order to investigate the error).

Apologies, and thank you for using Mutability Detector.



	at org.mutabilitydetector.checkers.UnhandledExceptionBuilder.unhandledException(UnhandledExceptionBuilder.java:54)
	at org.mutabilitydetector.checkers.CheckerRunner.attemptRecovery(CheckerRunner.java:79)
	at org.mutabilitydetector.checkers.CheckerRunner.run(CheckerRunner.java:66)
	at org.mutabilitydetector.checkers.AllChecksRunner.runCheckers(AllChecksRunner.java:65)
	at org.mutabilitydetector.ThreadUnsafeAnalysisSession.requestAnalysis(ThreadUnsafeAnalysisSession.java:118)
	at org.mutabilitydetector.ThreadUnsafeAnalysisSession.resultFor(ThreadUnsafeAnalysisSession.java:104)
	at org.jadira.cloning.mutability.MutabilityDetector.isImmutable(MutabilityDetector.java:65)
	at org.jadira.cloning.model.AbstractClassModel.<init>(AbstractClassModel.java:49)
	at org.jadira.cloning.model.UnsafeClassModel.<init>(UnsafeClassModel.java:42)
	at org.jadira.cloning.model.UnsafeClassModel.get(UnsafeClassModel.java:66)
	at org.jadira.cloning.implementor.UnsafeCloneStrategy.getClassModel(UnsafeCloneStrategy.java:49)
	at org.jadira.cloning.implementor.UnsafeCloneStrategy.getClassModel(UnsafeCloneStrategy.java:28)
	at org.jadira.cloning.implementor.AbstractCloneStrategy.doCloneStep(AbstractCloneStrategy.java:133)
	at org.jadira.cloning.implementor.AbstractCloneStrategy.clone(AbstractCloneStrategy.java:86)
	at org.jadira.cloning.BasicCloner.clone(BasicCloner.java:234)
	at org.jadira.cloning.BasicCloner.clone(BasicCloner.java:209)
	at infrastruktur.integration.isperson.personinformation.test.AdressTest.uppdateraLaggTillAdressImpl(AdressTest.java:433)
	at infrastruktur.integration.isperson.personinformation.test.AdressTest.kontrolleraUppdateraLaggTill(AdressTest.java:421)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at net.forsakringskassan.util.junit.JUnitLoggingRule$LoggerStatement.evaluate(JUnitLoggingRule.java:39)
	at net.forsakringskassan.util.ws.WSDumpRule$MethodStatement.evaluate(WSDumpRule.java:80)
	at net.forsakringskassan.util.junit.IgnoreRule$1.evaluate(IgnoreRule.java:52)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at net.forsakringskassan.util.junit.IgnoreRule$1.evaluate(IgnoreRule.java:52)
	at net.forsakringskassan.util.config.EnvironmentRule$1.evaluate(EnvironmentRule.java:42)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.IllegalArgumentException
	at org.mutabilitydetector.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:167)
	at org.mutabilitydetector.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at org.mutabilitydetector.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:468)
	at org.mutabilitydetector.checkers.CheckerRunner.analyseFromDefaultClassLoader(CheckerRunner.java:99)
	at org.mutabilitydetector.checkers.CheckerRunner.run(CheckerRunner.java:63)
	... 49 more


```

**Comment by Grundlefleck** [comment]
Thanks for reporting.

I'm unable to reproduce, it would be ideal if you could provide a small project replicating the issue, because I can't reproduce anything with just the source file. The source does not look like it contains anything that is unusual or esoteric. 

Would it be possible to let me know which version of Mutability Detector you are using, and also, what is the version of the class files compiled from `Adresspost.java`? 

Mutability Detector only gained support for JDK 8 bytecode from version 0.9.1 and onwards. If you are on a lower version, the ASM library used to read bytecode will throw an exception. It's an exception from ASM that is seen in this stack trace element:
  `at org.mutabilitydetector.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:167)`

If you are on a lower version, you could just try bumping to the latest (`0.9.6`) and see if it clears the issue.

**Comment by more10** [comment]
I get MutabilityDetector through org.jadira.cloning. 

I am jusing jdk 1.8.0_45.

**Comment by more10** [comment]
https://github.com/JadiraOrg/jadira/issues/54

**Comment by more10** [comment]
I was using an old verison of Jadira, they changed the org string :-) . Problem solved:

`<dependency org="org.jadira.reflection.cloning" name="cloning" rev="3.2.0.GA"/>`
