### ISSUE TITLE
Immutability test failing

### ISSUE THREAD

**Issue by harikrishna553** [MutabilityDetector/MutabilityDetector#86]
```
import java.util.ArrayList;
import java.util.List;

public final class Student {
	private final int id;
	private final String name;
	private final List<String> hobbies;

	Student(int id, String name, List<String> hobbies) {
		this.id = id;
		this.name = name;
		this.hobbies = hobbies;
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public List<String> getHobbies() {
		return new ArrayList<> (hobbies);
	}

}

```
When I tried to test for immutability using "assertImmutable(Student.class);", I am getting following error.

Attempt to wrap mutable collection using a non-whitelisted unmodifiable wrapper method. [Field: hobbies.....]

**Comment by Stephan202** [comment]
@harikrishna553, this class is not immutable because its constructor may be provided a mutable `List`. That way a `Student`'s `hobbies` can be modified after object construction.

**Comment by harikrishna553** [comment]
Thanks for your reply Stephen,
   Above class is immutable, When you see "getHobbies" method, I am returning a copy of hobbies list, not the reference to original one.

**Comment by harikrishna553** [comment]
Got your point. What if my constructor is like below.

```
Student(int id, String name, List<String> hobbies) {
		this.id = id;
		this.name = name;
		this.hobbies = new ArrayList<> (hobbies);
	}

```

**Comment by Stephan202** [comment]
@harikrishna553, yes, that would prevent outsiders from altering the list.

NB: note that `#getHobbies()` can be optimized a bit by returning `Collections.unmodifiableList(hobbies)`: that way no copy is made.

**Comment by harikrishna553** [comment]
I changed statement like below, and re run the test case.
`this.hobbies =Collections.unmodifiableList(hobbies);`

I am getting following error.
Attempts to wrap mutable collection type without safely performing a copy first [Field: hobbies.......]

How to make the test case pass for an immutable class with mutable fields like lists, set, arrays etc/.

**Comment by Stephan202** [comment]
My suggestion was to place the `Collections.unmodifiableList` invocation in the _getter_, not in the constructor. I.e.:

```java
import java.util.ArrayList;
import java.util.List;

public final class Student {
    private final int id;
    private final String name;
    private final List<String> hobbies;

    Student(int id, String name, List<String> hobbies) {
        this.id = id;
        this.name = name;
        this.hobbies = new ArrayList<>(hobbies);
    }

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public List<String> getHobbies() {
        return Collections.unmodifiableList(hobbies);
    }
}
```

That said, also have a look at Guava's [immutable collections](https://github.com/google/guava/wiki/ImmutableCollectionsExplained).

**Comment by harikrishna553** [comment]
Stephen,
  I got it what you are saying. I am still getting same error when testing **'assertImmutable(Student.class)'** the Student class.

```
org.mutabilitydetector.unittesting.MutabilityAssertionError: 
Expected: mutability.Student to be IMMUTABLE
     but: mutability.Student is actually NOT_IMMUTABLE
    Reasons:
        Field can have a mutable type (java.util.ArrayList) assigned to it. [Field: hobbies, Class: mutability.Student]
    Allowed reasons:
        None.
	at org.mutabilitydetector.unittesting.internal.AssertionReporter.assertThat(AssertionReporter.java:48)
	at org.mutabilitydetector.unittesting.MutabilityAsserter.assertImmutable(MutabilityAsserter.java:108)
	at org.mutabilitydetector.unittesting.MutabilityAssert.assertImmutable(MutabilityAssert.java:672)
	at mutability.TestMutability.checkMyClassIsImmutable(TestMutability.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Following i my Test class.

```
import static org.mutabilitydetector.unittesting.MutabilityAssert.assertImmutable;

import org.junit.Test;

public class TestMutability {

	@Test
	public void checkMyClassIsImmutable() {
		assertImmutable(Student.class);
	}
}

```

**Comment by Grundlefleck** [comment]
Hi,

While Stephan is correct that wrapping in unmodifiable in the getter makes
the class immutable, unfortunately Mutability Detector does not realise
that. It's analysis is a bit too naïve.

I suggest copying *and* wrapping in the constructor:

this.hobbies = Collections.unmodifiableList(new ArrayList<>(hobbies));

That should make the test pass and have other benefits:
- only one instance of the unmodifiable wrapper needs to be constructed
even if the getter is called many times
- it's harder to accidentally mutate the collection within this class

Let us know how that works for you.

Cheers!

P.S. really satisfying to see other people helping out on issues, thanks
Stephan.

**Comment by harikrishna553** [comment]
Thanks Grundlefleck , Stephen
  It solves the issue. Thanks for quick help.

**Comment by Stephan202** [comment]
@Grundlefleck, good suggestion on moving everything in the constructor; I almost feel dumb for not suggesting it myself. I guess it's because in my own code I always use Guava's immutable collections, so I haven't recently used the "JDK-only" approach. Anyway, happy to help!
